[package]
name = 'nft'
version = '1.0.0'

[dependencies]
MoveStdlib = { local = "../../../aptos-core/aptos-move/framework/move-stdlib" }
AptosFramework = { local = "../../../aptos-core/aptos-move/framework/aptos-framework"}
AptosToken = { local = "../../../aptos-core/aptos-move/framework/aptos-token"}

[addresses]
wav3 = "0x99c7b9b570e469c06ee9b00df8f3083b4d45e670dd6578746794ba39bbc2c262"